### ISSUE TITLE
intersphinx/sphinx-hoverref

### ISSUE THREAD

**Issue by zmoon** [xarray-contrib/xarray-tutorial#82]
For easier and more robust links to the xarray documentation.

Jupyter Book [uses it](https://github.com/executablebooks/jupyter-book/blob/d33a19848ed8e995ad596155e0d056f22eb89ebe/docs/_config.yml#L85) in their own docs, so it is definitely possible. I guess the downside is that the notebook would look more messy in Jupyter. But maybe [sphinx-codeautolink](https://sphinx-codeautolink.readthedocs.io/en/latest/) would work, at least for the code blocks.

**Comment by scottyhq** [comment]
Nice idea @zmoon this would definitely be interesting to try! We're in the midst of a pretty big revamp leading up to a scipy workshop in July, and just switched to jupyterbook so there is a fair amount in flux at the moment.

**Comment by zmoon** [comment]
What do you think about intersphinx references in the text? Would be nice to have the links, and reduced maintenance vs manually putting the links in, though for people running the notebooks in Jupyter the texts becomes a bit uglier.

**Comment by scottyhq** [comment]
I agree think the major drawback of Jupyter Book right now is the discrepancy between rendered notebooks on the website with lots of extra formatting compared to what is possible in Jupyter Lab. Numpy tutorials require only using CommonMark in notebook cells for this reason (https://github.com/numpy/numpy-tutorials#contributing)

My hunch is that the primary mode for consuming this material is on the website rather than Jupyter Lab, except for the case of workshops where everyone is on Jupyter Lab. And during workshops, the focus is on code cells (people can have the website open in another tab for the rendered version).

So I'm in favor of anything that makes for easier navigation on the website. Yet another convenience could be adding https://sphinx-hoverxref.readthedocs.io/en/latest/  https://blog.readthedocs.com/hoverxref-intersphinx.

**Comment by dcherian** [comment]
FWIW scikit-image does this very well with underlined links making it clear what you can click on: https://scikit-image.org/docs/stable/auto_examples/segmentation/plot_regionprops.html

**Comment by zmoon** [comment]
> scikit-image does this very well with underlined links

Sphinx-Gallery

**Comment by scottyhq** [comment]
I know this is closed, but I was re-visiting automatic hover previews today and noticed that https://github.com/readthedocs/sphinx-hoverxref is now deprecated in favor of a read-the-docs built in setting (https://docs.readthedocs.com/platform/stable/link-previews.html)... might be worth deploying to read-the-docs instead of github pages nowadays which would also simplify the preview workflow.

Also, I learned that chome actually has a hidden setting for link previews (https://winaero.com/enable-link-preview-chrome/) and in safari you can just 'force touch' links to show a preview!

<img width="1270" alt="Image" src="https://github.com/user-attachments/assets/b3ffce00-d5da-45dc-b943-8856f0539ad6" />
