### ISSUE TITLE
redirect old links...

### ISSUE THREAD

**Issue by jklymak** [xarray-contrib/xarray-tutorial#86]
Hi - the top search on google  for "xarray tutorial" is https://tutorial.xarray.dev/scipy-tutorial/00_overview.html, which is a 404.   Probably be good when things are removed to redirect the old address to a new appropriate place.  Not sure what technology you are using, but either keep the old page around with a canonical, replace it by an html, or do a server redirect.

**Comment by scottyhq** [comment]
Thanks for pointing this out @jklymak I'll open up a pull request with a couple fixes. 

1. can add a custom 404 page that leads people to the new homepage rather than the current github pages standard 404 (https://sphinx-notfound-page.readthedocs.io)
2. can use a sphinx extension ([sphinx-rediraffe](https://github.com/wpilibsuite/sphinxext-rediraffe)) https://github.com/executablebooks/jupyter-book/issues/1048#issuecomment-708024696

**Comment by dcherian** [comment]
:+1: I think we should redirect this overview link to our new "Getting Started" page.

**Comment by dcherian** [comment]
Wonderful, thanks Scott!
